name: jup-multiply

on:
  push:
    paths:
      - "jup-multiply.js"
  schedule:
    - cron: "* * * * *"

jobs:
  jup-multiply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ hashFiles('**/package-lock.json') }}

      - run: npm i
      - run: node jup-multiply.js
      - run: |
          git add jup-juiced-multiply.json jup-ethena-usde-multiply.json -f
          git commit -m "Update Jupiter Multiply data"
          git fetch --all
          git checkout gh-pages
          git checkout main jup-juiced-multiply.json jup-ethena-usde-multiply.json
          git add jup-juiced-multiply.json jup-ethena-usde-multiply.json -f
          git commit --amend --reset-author -m "Update data"
          git push --force
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
