name: jupiter-jlp

on:
  push:
    paths:
      - "jupiter-jlp.js"
  schedule:
    - cron: "* * * * *"

jobs:
  jupiter-jlp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ hashFiles('**/package-lock.json') }}

      - run: npm ci
      - run: node jupiter-jlp.js
      - run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"
          git add jupiter-jlp.json -f
          git commit -m "Update jupiter-jlp.json"
          git fetch --all
          git checkout gh-pages
          git checkout main jupiter-jlp.json
          git add jupiter-jlp.json -f
          git commit --amend -m "Update data"
          git push --force
