name: kamino-usdc

on:
  push:
    paths:
      - "kamino-usdc.js"
  schedule:
    - cron: "* * * * *"

jobs:
  kamino-usdc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ hashFiles('**/package-lock.json') }}

      - run: npm ci
      - run: node kamino-usdc.js
      - run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"
          git add kamino-usdc-alt.json -f
          git add kamino-usdc-jlp.json -f
          git add kamino-usdc-main.json -f
          git commit -m "Update kamino-usdc.json"
          git fetch --all
          git checkout gh-pages
          git checkout main kamino-usdc-alt.json
          git checkout main kamino-usdc-jlp.json
          git checkout main kamino-usdc-main.json
          git add kamino-usdc-alt.json -f
          git add kamino-usdc-jlp.json -f
          git add kamino-usdc-main.json -f
          git commit --amend -m "Update data"
          git push --force
