name: solend-usdc

on:
  push:
    paths:
      - "solend-usdc.js"
  schedule:
    - cron: "* * * * *"

jobs:
  solend-usdc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ hashFiles('**/package-lock.json') }}

      - run: npm ci
      - run: node solend-usdc.js
      - run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"
          git add solend-usdc.json -f
          git commit -m "Update solend-usdc.json"
          git fetch --all
          git checkout gh-pages
          git checkout main solend-usdc.json
          git add solend-usdc.json -f
          git commit --amend -m "Update data"
          git push --force
